#!/bin/bash


VERSION="1.0"
RELEASE_DATE="16/09/2026"
AUTHOR="ElSutien"


__clizepipe_one () {
  local red='1;31'
  local green='1;32'
  local yellow='1;33'
  local blue='1;34'
  local purple='1;35'
  local cyan='1;36'
  GREP_COLORS="ms=${!1}" grep --line-buffered --color=always -Ei "$|${2}"
}

__clizepipe () {
  [ "$#" -eq 0 ] && cat && return
  [ "$#" -lt 2 ] && printf 'clize: falta regex para el color: %s\n' "$1" >&2 && return 1

  local color="$1"
  local regex="$2"
  shift 2

  if [ "$#" -eq 0 ]; then
    __clizepipe_one "$color" "$regex"
  else
    __clizepipe_one "$color" "$regex" | __clizepipe "$@"
  fi
}


printHelp () {
  echo "Usage: clize [options] [COLOR REGEX ...] -- COMMAND [ARGS ...]"
  echo
  echo "Colorize the output of a command using regex."
  echo
  echo "Options:"
  echo "  --help      Show this help message"
  echo "  --version   Show version information"
  echo
  echo "COLOR is a predefined color. Available are:"
  echo "  red    -- EXAMPLE" | __clizepipe_one red EXAMPLE
  echo "  green  -- EXAMPLE" | __clizepipe_one green EXAMPLE
  echo "  yellow -- EXAMPLE" | __clizepipe_one yellow EXAMPLE
  echo "  blue   -- EXAMPLE" | __clizepipe_one blue EXAMPLE
  echo "  purple -- EXAMPLE" | __clizepipe_one purple EXAMPLE
  echo "  cyan   -- EXAMPLE" | __clizepipe_one cyan EXAMPLE
  echo
  echo "REGEX is a regular expression with Grep Extended Syntax."
}

printVersion () {
  echo "Clize v$VERSION ($RELEASE_DATE)"
  echo "By $AUTHOR"
}


clizeF () {
  local -a rules=()
  local -a cmd=()
  local found_separator=0

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --help)
        printHelp
        return 0
        ;;
        
      --version)
        printVersion
        return 0
        ;;
      
      --)
        found_separator=1
        shift
        cmd=("$@")
        break
        ;;

      *)
        if [ "$#" -lt 3 ]; then
          printf 'Usage: clize COLOR REGEX [COLOR REGEX ...] -- COMMAND [ARGS...]\n' >&2
          return 1
        fi

        rules+=("$1" "$2")
        shift 2
        ;;
    esac
  done

  if [ "$found_separator" -ne 1 ]; then
    printf 'clize: falta separador --\n' >&2
    printf 'Uso: clize COLOR REGEX [COLOR REGEX ...] -- COMANDO [ARGS...]\n' >&2
    return 1
  fi

  if [ "${#cmd[@]}" -eq 0 ]; then
    printf 'clize: falta comando despues de --\n' >&2
    return 1
  fi

  script -qefc "$(printf '%q ' "${cmd[@]}")" /dev/null | __clizepipe "${rules[@]}"
}


clizeF $*